# Generated by Django 5.2.6 on 2025-12-15 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='NOMBRE_USUARIO', max_length=50, unique=True)),
                ('clave_hash', models.CharField(db_column='CLAVE_HASH', max_length=255)),
                ('nombre_completo', models.CharField(db_column='NOMBRE_COMPLETO', max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(db_column='ID_COMUNA', primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(db_column='NOMBRE_COMUNA', max_length=50)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('codigo_moto', models.IntegerField(db_column='CODIGO_MOTO', primary_key=True, serialize=False)),
                ('patente', models.CharField(db_column='PATENTE', max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, db_column='MARCA', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='MODELO', max_length=50, null=True)),
                ('color', models.CharField(blank=True, db_column='COLOR', max_length=20, null=True)),
                ('anio', models.TextField(blank=True, db_column='ANIO', null=True)),
                ('numero_chasis', models.CharField(db_column='NUMERO_CHASIS', max_length=17, unique=True)),
                ('motor', models.CharField(blank=True, db_column='MOTOR', max_length=50, null=True)),
                ('propietario_moto', models.CharField(db_column='PROPIETARIO_MOTO', max_length=9)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'db_table': 'moto',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='ID_REGION', primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(db_column='NOMBRE_REGION', max_length=50)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('OPERADORA', 'Operadora')], db_column='NOMBRE_ROL', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoDespacho',
            fields=[
                ('id_tipo_despacho', models.AutoField(db_column='ID_TIPO_DESPACHO', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='NOMBRE_TIPO', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Despacho',
                'verbose_name_plural': 'Tipos de Despacho',
                'db_table': 'tipo_despacho',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('codigo_farmacia', models.IntegerField(db_column='CODIGO_FARMACIA', primary_key=True, serialize=False)),
                ('nombre_farmacia', models.CharField(db_column='NOMBRE_FARMACIA', max_length=50)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=150)),
                ('horario_apertura', models.TimeField(blank=True, db_column='HORARIO_APERTURA', null=True)),
                ('horario_cierre', models.TimeField(blank=True, db_column='HORARIO_CIERRE', null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20, unique=True)),
                ('latitud', models.DecimalField(blank=True, db_column='LATITUD', decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, db_column='LONGITUD', decimal_places=6, max_digits=9, null=True)),
                ('id_comuna', models.ForeignKey(blank=True, db_column='ID_COMUNA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.comuna')),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'db_table': 'farmacia',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(db_column='ID_DESPACHO', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('direccion_entrega', models.CharField(db_column='DIRECCION_ENTREGA', max_length=200)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('FALLIDO', 'Fallido')], db_column='ESTADO', default='CREADO', max_length=10)),
                ('codigo_orden_farmacia', models.CharField(blank=True, db_column='CODIGO_ORDEN_FARMACIA', max_length=50, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, db_column='FECHA_FINALIZACION', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='OBSERVACIONES', null=True)),
                ('id_despacho_original', models.ForeignKey(blank=True, db_column='ID_DESPACHO_ORIGINAL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reenvios', to='AppDiscopro.despacho')),
                ('id_farmacia_origen', models.ForeignKey(db_column='ID_FARMACIA_ORIGEN', on_delete=django.db.models.deletion.DO_NOTHING, related_name='despachos_origen', to='AppDiscopro.farmacia')),
                ('id_farmacia_origen_secundaria', models.ForeignKey(blank=True, db_column='ID_FARMACIA_ORIGEN_SECUNDARIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despachos_secundarios', to='AppDiscopro.farmacia')),
                ('id_moto', models.ForeignKey(db_column='ID_MOTO', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.moto')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'db_table': 'despacho',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionMotoristaFarmacia',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('id_farmacia', models.ForeignKey(db_column='ID_FARMACIA', on_delete=django.db.models.deletion.CASCADE, to='AppDiscopro.farmacia')),
            ],
            options={
                'verbose_name': 'Asignación Motorista-Farmacia',
                'verbose_name_plural': 'Asignaciones Motorista-Farmacia',
                'db_table': 'asignacion_motorista_farmacia',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(db_column='ID_INCIDENCIA', primary_key=True, serialize=False)),
                ('tipo_incidencia', models.CharField(choices=[('CLIENTE_AUSENTE', 'Cliente Ausente'), ('DIRECCION_INCORRECTA', 'Dirección Incorrecta'), ('CLIENTE_RECHAZA', 'Cliente Rechaza Pedido'), ('ACCIDENTE', 'Accidente'), ('FALLA_MOTO', 'Falla Mecánica de Moto'), ('PRODUCTO_INCORRECTO', 'Producto Incorrecto'), ('DEMORA_TRAFICO', 'Demora por Tráfico'), ('OTRO', 'Otro')], db_column='TIPO_INCIDENCIA', max_length=30)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
                ('fecha_incidencia', models.DateTimeField(auto_now_add=True, db_column='FECHA_INCIDENCIA')),
                ('resuelto', models.BooleanField(db_column='RESUELTO', default=False)),
                ('id_despacho', models.ForeignKey(db_column='ID_DESPACHO', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='AppDiscopro.despacho')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
                'ordering': ['-fecha_incidencia'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('codigo_motorista', models.IntegerField(db_column='CODIGO_MOTORISTA', primary_key=True, serialize=False)),
                ('rut', models.CharField(db_column='RUT', max_length=12, unique=True)),
                ('pasaporte', models.CharField(blank=True, db_column='PASAPORTE', max_length=12, null=True, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=30)),
                ('apellido_paterno', models.CharField(db_column='APELLIDO_PATERNO', max_length=30)),
                ('apellido_materno', models.CharField(db_column='APELLIDO_MATERNO', max_length=30)),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO')),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=100, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20)),
                ('correo', models.CharField(db_column='CORREO', max_length=50, unique=True)),
                ('incluye_moto_personal', models.IntegerField(db_column='INCLUYE_MOTO_PERSONAL')),
                ('id_comuna', models.ForeignKey(blank=True, db_column='ID_COMUNA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.comuna')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'motorista',
            },
        ),
        migrations.AddField(
            model_name='moto',
            name='id_motorista_asignado',
            field=models.OneToOneField(blank=True, db_column='ID_MOTORISTA_ASIGNADO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista'),
        ),
        migrations.CreateModel(
            name='LicenciaMotorista',
            fields=[
                ('id_licencia', models.AutoField(db_column='ID_LICENCIA', primary_key=True, serialize=False)),
                ('tipo_licencia', models.CharField(blank=True, db_column='TIPO_LICENCIA', max_length=10, null=True)),
                ('fecha_control', models.DateField(blank=True, db_column='FECHA_CONTROL', null=True)),
                ('fecha_vencimiento', models.DateField(db_column='FECHA_VENCIMIENTO')),
                ('ruta_adjunto_archivo', models.CharField(blank=True, db_column='RUTA_ADJUNTO_ARCHIVO', max_length=255, null=True)),
                ('id_motorista', models.OneToOneField(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista')),
            ],
            options={
                'verbose_name': 'Licencia de Motorista',
                'verbose_name_plural': 'Licencias de Motoristas',
                'db_table': 'licencia_motorista',
            },
        ),
        migrations.AddField(
            model_name='farmacia',
            name='motoristas_asignados',
            field=models.ManyToManyField(related_name='farmacias_asignadas', through='AppDiscopro.AsignacionMotoristaFarmacia', to='AppDiscopro.motorista'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_motorista',
            field=models.ForeignKey(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista'),
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto', models.AutoField(db_column='ID_CONTACTO', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='NOMBRE_COMPLETO', max_length=100)),
                ('parentesco', models.CharField(blank=True, db_column='PARENTESCO', max_length=50, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20)),
                ('id_motorista', models.ForeignKey(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
                'db_table': 'contacto_emergencia',
            },
        ),
        migrations.AddField(
            model_name='asignacionmotoristafarmacia',
            name='id_motorista',
            field=models.ForeignKey(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.CASCADE, to='AppDiscopro.motorista'),
        ),
        migrations.CreateModel(
            name='RecetaDespacho',
            fields=[
                ('id_receta', models.AutoField(db_column='ID_RECETA', primary_key=True, serialize=False)),
                ('numero_receta', models.CharField(blank=True, db_column='NUMERO_RECETA', max_length=50, null=True)),
                ('nombre_medico', models.CharField(blank=True, db_column='NOMBRE_MEDICO', max_length=100, null=True)),
                ('fecha_emision', models.DateField(blank=True, db_column='FECHA_EMISION', null=True)),
                ('ruta_archivo', models.CharField(blank=True, db_column='RUTA_ARCHIVO', max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='OBSERVACIONES', null=True)),
                ('id_despacho', models.OneToOneField(db_column='ID_DESPACHO', on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='AppDiscopro.despacho')),
            ],
            options={
                'verbose_name': 'Receta de Despacho',
                'verbose_name_plural': 'Recetas de Despacho',
                'db_table': 'receta_despacho',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='ID_REGION', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.region'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_tipo_despacho',
            field=models.ForeignKey(db_column='ID_TIPO_DESPACHO', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.tipodespacho'),
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='NOMBRE_USUARIO', max_length=50, unique=True)),
                ('correo', models.EmailField(db_column='CORREO', max_length=100, unique=True)),
                ('nombre_completo', models.CharField(db_column='NOMBRE_COMPLETO', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='FECHA_CREACION', default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(blank=True, db_column='ULTIMO_ACCESO', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece el usuario', related_name='appdiscopro_usuariopersonalizado_set', to='auth.group')),
                ('id_rol', models.ForeignKey(db_column='ID_ROL', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='AppDiscopro.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos del usuario', related_name='appdiscopro_usuariopersonalizado_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario_personalizado',
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='CREADO_POR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentacionMoto',
            fields=[
                ('id_documento', models.AutoField(db_column='ID_DOCUMENTO', primary_key=True, serialize=False)),
                ('anio', models.IntegerField(db_column='ANIO')),
                ('tipo_documento', models.CharField(db_column='TIPO_DOCUMENTO', max_length=19)),
                ('ruta_adjunto_archivo', models.CharField(blank=True, db_column='RUTA_ADJUNTO_ARCHIVO', max_length=255, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='FECHA_VENCIMIENTO', null=True)),
                ('id_moto', models.ForeignKey(db_column='ID_MOTO', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.moto')),
            ],
            options={
                'verbose_name': 'Documentación de Moto',
                'verbose_name_plural': 'Documentación de Motos',
                'db_table': 'documentacion_moto',
                'unique_together': {('id_moto', 'anio', 'tipo_documento')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignacionmotoristafarmacia',
            unique_together={('id_farmacia', 'id_motorista')},
        ),
    ]
