# Generated by Django 5.2.6 on 2025-10-16 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(db_column='ID_COMUNA', primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(db_column='NOMBRE_COMUNA', max_length=50)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='ID_REGION', primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(db_column='NOMBRE_REGION', max_length=50)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='NOMBRE_ROL', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoDespacho',
            fields=[
                ('id_tipo_despacho', models.IntegerField(db_column='ID_TIPO_DESPACHO', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='NOMBRE_TIPO', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_despacho',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('codigo_farmacia', models.IntegerField(db_column='CODIGO_FARMACIA', primary_key=True, serialize=False)),
                ('nombre_farmacia', models.CharField(db_column='NOMBRE_FARMACIA', max_length=50)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=150)),
                ('horario_apertura', models.TimeField(blank=True, db_column='HORARIO_APERTURA', null=True)),
                ('horario_cierre', models.TimeField(blank=True, db_column='HORARIO_CIERRE', null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20, unique=True)),
                ('latitud', models.DecimalField(blank=True, db_column='LATITUD', decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, db_column='LONGITUD', decimal_places=6, max_digits=9, null=True)),
                ('id_comuna', models.ForeignKey(blank=True, db_column='ID_COMUNA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.comuna')),
            ],
            options={
                'db_table': 'farmacia',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('codigo_motorista', models.IntegerField(db_column='CODIGO_MOTORISTA', primary_key=True, serialize=False)),
                ('rut', models.CharField(db_column='RUT', max_length=12, unique=True)),
                ('pasaporte', models.CharField(blank=True, db_column='PASAPORTE', max_length=12, null=True, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=30)),
                ('apellido_paterno', models.CharField(db_column='APELLIDO_PATERNO', max_length=30)),
                ('apellido_materno', models.CharField(db_column='APELLIDO_MATERNO', max_length=30)),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO')),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=100, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20)),
                ('correo', models.CharField(db_column='CORREO', max_length=50, unique=True)),
                ('incluye_moto_personal', models.IntegerField(db_column='INCLUYE_MOTO_PERSONAL')),
                ('id_comuna', models.ForeignKey(blank=True, db_column='ID_COMUNA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.comuna')),
            ],
            options={
                'db_table': 'motorista',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('codigo_moto', models.IntegerField(db_column='CODIGO_MOTO', primary_key=True, serialize=False)),
                ('patente', models.CharField(db_column='PATENTE', max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, db_column='MARCA', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='MODELO', max_length=50, null=True)),
                ('color', models.CharField(blank=True, db_column='COLOR', max_length=20, null=True)),
                ('anio', models.TextField(blank=True, db_column='ANIO', null=True)),
                ('numero_chasis', models.CharField(db_column='NUMERO_CHASIS', max_length=17, unique=True)),
                ('motor', models.CharField(blank=True, db_column='MOTOR', max_length=50, null=True)),
                ('propietario_moto', models.CharField(db_column='PROPIETARIO_MOTO', max_length=9)),
                ('id_motorista_asignado', models.OneToOneField(blank=True, db_column='ID_MOTORISTA_ASIGNADO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista')),
            ],
            options={
                'db_table': 'moto',
            },
        ),
        migrations.CreateModel(
            name='LicenciaMotorista',
            fields=[
                ('id_licencia', models.AutoField(db_column='ID_LICENCIA', primary_key=True, serialize=False)),
                ('tipo_licencia', models.CharField(blank=True, db_column='TIPO_LICENCIA', max_length=10, null=True)),
                ('fecha_control', models.DateField(blank=True, db_column='FECHA_CONTROL', null=True)),
                ('fecha_vencimiento', models.DateField(db_column='FECHA_VENCIMIENTO')),
                ('ruta_adjunto_archivo', models.CharField(blank=True, db_column='RUTA_ADJUNTO_ARCHIVO', max_length=255, null=True)),
                ('id_motorista', models.OneToOneField(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista')),
            ],
            options={
                'db_table': 'licencia_motorista',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto', models.AutoField(db_column='ID_CONTACTO', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='NOMBRE_COMPLETO', max_length=100)),
                ('parentesco', models.CharField(blank=True, db_column='PARENTESCO', max_length=50, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=20)),
                ('id_motorista', models.ForeignKey(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista')),
            ],
            options={
                'db_table': 'contacto_emergencia',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='ID_REGION', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.region'),
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.IntegerField(db_column='ID_DESPACHO', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(db_column='FECHA_CREACION')),
                ('direccion_entrega', models.CharField(db_column='DIRECCION_ENTREGA', max_length=200)),
                ('estado', models.CharField(db_column='ESTADO', max_length=10)),
                ('codigo_orden_farmacia', models.CharField(blank=True, db_column='CODIGO_ORDEN_FARMACIA', max_length=50, null=True)),
                ('id_farmacia_origen', models.ForeignKey(db_column='ID_FARMACIA_ORIGEN', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.farmacia')),
                ('id_farmacia_origen_secundaria', models.ForeignKey(blank=True, db_column='ID_FARMACIA_ORIGEN_SECUNDARIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despacho_id_farmacia_origen_secundaria_set', to='AppDiscopro.farmacia')),
                ('id_moto', models.ForeignKey(db_column='ID_MOTO', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.moto')),
                ('id_motorista', models.ForeignKey(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.motorista')),
                ('id_tipo_despacho', models.ForeignKey(db_column='ID_TIPO_DESPACHO', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.tipodespacho')),
            ],
            options={
                'db_table': 'despacho',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='NOMBRE_USUARIO', max_length=50, unique=True)),
                ('clave_hash', models.CharField(db_column='CLAVE_HASH', max_length=255)),
                ('nombre_completo', models.CharField(db_column='NOMBRE_COMPLETO', max_length=100)),
                ('id_rol', models.ForeignKey(db_column='ID_ROL', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='DocumentacionMoto',
            fields=[
                ('id_documento', models.AutoField(db_column='ID_DOCUMENTO', primary_key=True, serialize=False)),
                ('anio', models.IntegerField(db_column='ANIO')),
                ('tipo_documento', models.CharField(db_column='TIPO_DOCUMENTO', max_length=19)),
                ('ruta_adjunto_archivo', models.CharField(blank=True, db_column='RUTA_ADJUNTO_ARCHIVO', max_length=255, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='FECHA_VENCIMIENTO', null=True)),
                ('id_moto', models.ForeignKey(db_column='ID_MOTO', on_delete=django.db.models.deletion.DO_NOTHING, to='AppDiscopro.moto')),
            ],
            options={
                'db_table': 'documentacion_moto',
                'unique_together': {('id_moto', 'anio', 'tipo_documento')},
            },
        ),
    ]
