# Generated by Django 5.2.6 on 2025-10-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiscopro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMotoristaFarmacia',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('id_farmacia', models.ForeignKey(db_column='ID_FARMACIA', on_delete=django.db.models.deletion.CASCADE, to='AppDiscopro.farmacia')),
                ('id_motorista', models.ForeignKey(db_column='ID_MOTORISTA', on_delete=django.db.models.deletion.CASCADE, to='AppDiscopro.motorista')),
            ],
            options={
                'db_table': 'asignacion_motorista_farmacia',
                'unique_together': {('id_farmacia', 'id_motorista')},
            },
        ),
        migrations.AddField(
            model_name='farmacia',
            name='motoristas_asignados',
            field=models.ManyToManyField(related_name='farmacias_asignadas', through='AppDiscopro.AsignacionMotoristaFarmacia', to='AppDiscopro.motorista'),
        ),
    ]
