# Generated by Django 5.2.6 on 2025-11-06 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiscopro', '0002_asignacionmotoristafarmacia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despacho',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='despacho',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, db_column='FECHA_FINALIZACION', null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_despacho_original',
            field=models.ForeignKey(blank=True, db_column='ID_DESPACHO_ORIGINAL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reenvios', to='AppDiscopro.despacho'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='observaciones',
            field=models.TextField(blank=True, db_column='OBSERVACIONES', null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('FALLIDO', 'Fallido')], db_column='ESTADO', default='CREADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='id_despacho',
            field=models.AutoField(db_column='ID_DESPACHO', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='id_farmacia_origen',
            field=models.ForeignKey(db_column='ID_FARMACIA_ORIGEN', on_delete=django.db.models.deletion.DO_NOTHING, related_name='despachos_origen', to='AppDiscopro.farmacia'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='id_farmacia_origen_secundaria',
            field=models.ForeignKey(blank=True, db_column='ID_FARMACIA_ORIGEN_SECUNDARIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='despachos_secundarios', to='AppDiscopro.farmacia'),
        ),
        migrations.AlterField(
            model_name='tipodespacho',
            name='id_tipo_despacho',
            field=models.AutoField(db_column='ID_TIPO_DESPACHO', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(db_column='ID_INCIDENCIA', primary_key=True, serialize=False)),
                ('tipo_incidencia', models.CharField(choices=[('CLIENTE_AUSENTE', 'Cliente Ausente'), ('DIRECCION_INCORRECTA', 'Dirección Incorrecta'), ('CLIENTE_RECHAZA', 'Cliente Rechaza Pedido'), ('ACCIDENTE', 'Accidente'), ('FALLA_MOTO', 'Falla Mecánica de Moto'), ('PRODUCTO_INCORRECTO', 'Producto Incorrecto'), ('DEMORA_TRAFICO', 'Demora por Tráfico'), ('OTRO', 'Otro')], db_column='TIPO_INCIDENCIA', max_length=30)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
                ('fecha_incidencia', models.DateTimeField(auto_now_add=True, db_column='FECHA_INCIDENCIA')),
                ('resuelto', models.BooleanField(db_column='RESUELTO', default=False)),
                ('id_despacho', models.ForeignKey(db_column='ID_DESPACHO', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='AppDiscopro.despacho')),
            ],
            options={
                'db_table': 'incidencia',
                'ordering': ['-fecha_incidencia'],
            },
        ),
        migrations.CreateModel(
            name='RecetaDespacho',
            fields=[
                ('id_receta', models.AutoField(db_column='ID_RECETA', primary_key=True, serialize=False)),
                ('numero_receta', models.CharField(blank=True, db_column='NUMERO_RECETA', max_length=50, null=True)),
                ('nombre_medico', models.CharField(blank=True, db_column='NOMBRE_MEDICO', max_length=100, null=True)),
                ('fecha_emision', models.DateField(blank=True, db_column='FECHA_EMISION', null=True)),
                ('ruta_archivo', models.CharField(blank=True, db_column='RUTA_ARCHIVO', max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='OBSERVACIONES', null=True)),
                ('id_despacho', models.OneToOneField(db_column='ID_DESPACHO', on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='AppDiscopro.despacho')),
            ],
            options={
                'db_table': 'receta_despacho',
            },
        ),
    ]
